### ISSUE TITLE
Doubts about PSNR metrics

### ISSUE THREAD

**Issue by bugerry87** [NJUVISION/SparsePCGC#1]
Dear Authors,

I'm wondering and would like to ask how you calculated the PSNR metrics on the KITTI Dataset.
If I test the G-PCC with its standard parameters and evaluate it with [https://github.com/mauriceqch/geo_dist](https://github.com/mauriceqch/geo_dist), than it would have a D2 PSNR of about 70dB at about 14bpp.
You show a G-PCC performance of about 90dB at 14bpp?
In my experience the G-PCC requires a voxel size of less then 1mm to achieve a PSNR of 90dB having 20bpp and beyond.
The VoxelContextNet stated that they fixed the peak in their PSNR to 1m. Did you do the same?

Furthermore, I wondering  why you test on a pre-quantized point-cloud of 1mm.

PS: Personally I don't like the PSNR metric for measuring the Point Cloud quality. Every paper has its own interpretation and makes them incomparable. Furthermore, the value itself tells nothing as a standalone - is 100dB high or low? Well, it always depends on what the peak was. So it is a very relative metric.

Thx in advance
Gerry

**Comment by yydlmzyz** [comment]
Hi, Gerry,

We follow the common test condition of MPEG G-PCC (https://box.nju.edu.cn/f/82b25a75e63c49fabfb0/) for testing.
The raw floating-point coordinates are quantized to 1mm by multipying by 1000 and rounding.
The PSNR metric tool is pc_error (https://box.nju.edu.cn/f/159e38533c0d4be980a6/)
The peak value is 30000, which is set according to the CTC mentioned above.
We use the settings of MPEG G-PCC, instead of the settings of VoxelContext-Net.
I agree with you that PSNR metric is relative and may lead to incomparable results.

Best regards,
Jianqiang

**Comment by bugerry87** [comment]
Hey,
Thanks for reply and thanks for sharing the CTC doc.
I saw it in your references but was not able to find it based on that information.

Ookay I was using https://github.com/mauriceqch/geo_dist from the author of P2Plane PSNR.
However, I assume it has a "bug". It seems like it takes the distance of the very next neighbor after the nearest neighbor as peak rather than as stated in the paper i.e. the max distances among the k-nearest neighbors.
Although, otherwise k would alter p.
Using p=30m is definitely more stable.

Nonetheless, since I struggled about the peak I reversed the it from your results by
sqrt(10^(PSNR/10) * MSE)
that tells your peak was constantly ~51m including the TMC13 samples.

But neverminded I will now double check with the CTC and their metric tool.
Thanks a lot.
